Add command line argument `--only-lint-under-config-dir`
suo/lintrunner pull request #60
Opened 2023-08-03 02:26 UTC by PaliC

Add command line argument `--only-lint-under-config-dir`

Adds command line argument `--only-lint-under-config-dir` option to only lint under the configuration directory. For simplicty this argument can also be added to a configuration file as well.

2023-08-03 17:16 UTC, ZainRizvi requested changes
I'm not understanding what this feature is supposed to do: 
- Which config file does it refer to? The toml file?
- Why would you want to only lint under that directory?
- Would a better argument instead be: --lint-dirs which accepts a comma separated list of paths to lint (and nothing else gets linted)

2023-08-03 18:19 UTC, PaliC commented
@ZainRizvi 
1. Yeah its the toml file
2. Dm'ed but the answer is that internal is weird.

2023-08-03 22:03 UTC, ZainRizvi approved these changes
Approved as per offline conversation, since this appears to match the design of lintrunner. 

Final call on what you'd prefer here is yours @suo

2023-08-14 20:57 UTC, suo approved these changes

2023-08-22 23:50 UTC, merged